// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/Misoten-B/airship-backend/config"
	"github.com/Misoten-B/airship-backend/internal/application/usecase/ar_assets"
	"github.com/Misoten-B/airship-backend/internal/domain/ar_assets/service"
	service3 "github.com/Misoten-B/airship-backend/internal/domain/three_dimentional_model/service"
	service2 "github.com/Misoten-B/airship-backend/internal/domain/voice/service"
	"github.com/Misoten-B/airship-backend/internal/infrastructure/ar_assets"
	"github.com/Misoten-B/airship-backend/internal/infrastructure/three_dimentional_model"
	"github.com/Misoten-B/airship-backend/internal/infrastructure/voice"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeCreateARAssetsUsecaseForDev() *usecase.ARAssetsUsecaseImpl {
	mockARAssetsRepository := service.NewMockARAssetsRepository()
	mockQRCodeImageStorage := service.NewMockQRCodeImageStorage()
	mockVoiceModelAdapter := service2.NewMockVoiceModelAdapter()
	mockVoiceRepository := service2.NewMockVoiceRepository()
	voiceServiceImpl := service2.NewVoiceServiceImpl(mockVoiceRepository)
	mockThreeDimentionalModelRepository := service3.NewMockThreeDimentionalModelRepository()
	threeDimentionalModelServiceImpl := service3.NewThreeDimentionalModelServiceImpl(mockThreeDimentionalModelRepository)
	arAssetsUsecaseImpl := usecase.NewARAssetsUsecaseImpl(mockARAssetsRepository, mockQRCodeImageStorage, mockVoiceModelAdapter, voiceServiceImpl, threeDimentionalModelServiceImpl)
	return arAssetsUsecaseImpl
}

func InitializeCreateARAssetsUsecaseForProd(db *gorm.DB, config2 *config.Config) *usecase.ARAssetsUsecaseImpl {
	gormARAssetsRepository := arassets.NewGormARAssetsRepository(db)
	azureQRCodeImageStorage := arassets.NewAzureQRCodeImageStorage(config2)
	externalAPIVoiceModelAdapter := voice.NewExternalAPIVoiceModelAdapter()
	gormVoiceRepository := voice.NewGormVoiceRepository(db)
	voiceServiceImpl := service2.NewVoiceServiceImpl(gormVoiceRepository)
	gormThreeDimentionalModelRepository := threedimentionalmodel.NewGormThreeDimentionalModelRepository(db)
	threeDimentionalModelServiceImpl := service3.NewThreeDimentionalModelServiceImpl(gormThreeDimentionalModelRepository)
	arAssetsUsecaseImpl := usecase.NewARAssetsUsecaseImpl(gormARAssetsRepository, azureQRCodeImageStorage, externalAPIVoiceModelAdapter, voiceServiceImpl, threeDimentionalModelServiceImpl)
	return arAssetsUsecaseImpl
}

// wire.go:

// CreateARAssetsUsecaseForDev は開発環境用のARAssetsUsecaseを生成します。
// 現状、このファイルに記述されていますが、将来的にはユースケースのファクトリ部分に移動することも
// 検討しています。
var CreateARAssetsUsecaseForDev = wire.NewSet(usecase.NewARAssetsUsecaseImpl, service.NewMockARAssetsRepository, wire.Bind(new(service.ARAssetsRepository), new(*service.MockARAssetsRepository)), service.NewMockQRCodeImageStorage, wire.Bind(new(service.QRCodeImageStorage), new(*service.MockQRCodeImageStorage)), service2.NewMockVoiceModelAdapter, wire.Bind(new(service2.VoiceModelAdapter), new(*service2.MockVoiceModelAdapter)), service2.NewVoiceServiceImpl, wire.Bind(new(service2.VoiceService), new(*service2.VoiceServiceImpl)), service2.NewMockVoiceRepository, wire.Bind(new(service2.VoiceRepository), new(*service2.MockVoiceRepository)), service3.NewThreeDimentionalModelServiceImpl, wire.Bind(new(service3.ThreeDimentionalModelService), new(*service3.ThreeDimentionalModelServiceImpl)), service3.NewMockThreeDimentionalModelRepository, wire.Bind(new(service3.ThreeDimentionalModelRepository), new(*service3.MockThreeDimentionalModelRepository)))

var CreateARAssetsUsecaseForProd = wire.NewSet(usecase.NewARAssetsUsecaseImpl, arassets.NewGormARAssetsRepository, wire.Bind(new(service.ARAssetsRepository), new(*arassets.GormARAssetsRepository)), arassets.NewAzureQRCodeImageStorage, wire.Bind(new(service.QRCodeImageStorage), new(*arassets.AzureQRCodeImageStorage)), voice.NewExternalAPIVoiceModelAdapter, wire.Bind(new(service2.VoiceModelAdapter), new(*voice.ExternalAPIVoiceModelAdapter)), service2.NewVoiceServiceImpl, wire.Bind(new(service2.VoiceService), new(*service2.VoiceServiceImpl)), voice.NewGormVoiceRepository, wire.Bind(new(service2.VoiceRepository), new(*voice.GormVoiceRepository)), service3.NewThreeDimentionalModelServiceImpl, wire.Bind(new(service3.ThreeDimentionalModelService), new(*service3.ThreeDimentionalModelServiceImpl)), threedimentionalmodel.NewGormThreeDimentionalModelRepository, wire.Bind(new(service3.ThreeDimentionalModelRepository), new(*threedimentionalmodel.GormThreeDimentionalModelRepository)))
