services:
  golang:
    build:
      context: .
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    environment:
      DB_HOST: database
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: airship
      MYSQL_USER: user
      MYSQL_PASSWORD: password