services:
  # golang:
  golang:
    build:
      context: .
      target: dev
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: gopkg
        target: /go/pkg/mod
    depends_on:
      - database
    environment:
      DB_HOST: database
  
  # database:
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: airship
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  gopkg: