version: '3'

tasks:
  run:db:
    desc: Run Database with docker compose
    cmds:
      - docker compose up
  run:app:
    desc: Run Application with air
    cmds:
      - sleep 3
      - air -c .air.toml
  run:
    desc: Run Database and Application
    deps: [run:db, run:app]
  generate:
    desc: run go generate
    cmds:
      - go generate
  db:migrate:
    desc: Run Database Migration
    deps: [run:db]
    cmds:
      - sleep 3
      - go run ./scripts/migrate/main.go
  db:seed:
    desc: Run Database Seed
    deps: [run:db]
    cmds:
      - sleep 3
      - go run ./scripts/seed/main.go