version: '3'

tasks:
  run:
    desc: Run docker compose
    cmds:
      - docker compose up {{ .CLI_ARGS }}
  generate:
    desc: Run go generate
    cmds:
      - docker compose exec golang go generate
  database:migrate:
    desc: Run database migrations
    cmds:
      - docker compose exec golang go run ./scripts/migrate/main.go
  database:seed:
    desc: Run database seed
    cmds:
      - docker compose exec golang go run ./scripts/seed/main.go