// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/ar_assets/{ar_assets_id}": {
            "get": {
                "tags": [
                    "ArAssets"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ArAssets ID",
                        "name": "ar_assets_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ArAssetsResponse"
                        }
                    }
                }
            }
        },
        "/v1/business_card_parts_coordinates": {
            "get": {
                "tags": [
                    "BusinessCardPartsCoordinate"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.BusinessCardPartsCoordinateResponse"
                            }
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "create user",
                        "name": "CreateUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/ar_assets": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ArAssets"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ArAssetsResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "ArAssets"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file to be uploaded",
                        "name": "qrcodeIcon",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "description",
                        "name": "speaking_description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "url",
                        "name": "three_dimentional_ID",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ArAssetsResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/ar_assets/{ar_assets_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ArAssets"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ArAssets ID",
                        "name": "ar_assets_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ArAssetsResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "ArAssets"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "description",
                        "name": "speaking_description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "url",
                        "name": "three_dimentional_ID",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ArAssets ID",
                        "name": "ar_assets_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file to be uploaded",
                        "name": "qrcodeIcon",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ArAssetsResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ArAssets"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ArAssets ID",
                        "name": "ar_assets_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/users/business_card_backgrounds": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "BusinessCardBackground"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.BackgroundResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "BusinessCardBackground"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file to be uploaded",
                        "name": "BusinessCardBackgroundImage",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "description": "BusinessCardBackground",
                        "name": "dto.CreateBackgroundRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateBackgroundRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.BackgroundResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/business_cards": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "BusinessCard"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.BusinessCardResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "BusinessCard"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "東京都渋谷区神南1-1-1",
                        "x-nullable": true,
                        "name": "address",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "ar_assets_id",
                        "x-nullable": true,
                        "description": "ar assets",
                        "name": "ar_assets_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "id",
                        "x-nullable": true,
                        "description": "background",
                        "name": "business_card_background_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "会社",
                        "x-nullable": true,
                        "name": "business_card_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "id",
                        "x-nullable": true,
                        "description": "business card",
                        "name": "business_card_parts_coordinate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "会社名",
                        "x-nullable": true,
                        "name": "company_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "部署",
                        "x-nullable": true,
                        "name": "department",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "名前",
                        "x-nullable": true,
                        "name": "display_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "sample@example.com",
                        "x-nullable": true,
                        "name": "email",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "役職",
                        "x-nullable": true,
                        "name": "official_position",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "090-1234-5678",
                        "x-nullable": true,
                        "name": "phone_number",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "123-4567",
                        "x-nullable": true,
                        "name": "postal_code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "url",
                        "x-nullable": true,
                        "name": "qrcode_image_path",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.BusinessCardResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/business_cards/{business_card_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "BusinessCard"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "BusinessCard ID",
                        "name": "business_card_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BusinessCardResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "BusinessCard"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "BusinessCard ID",
                        "name": "business_card_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file to be uploaded",
                        "name": "BusinessCardBackgroundImage",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "東京都渋谷区神南1-1-1",
                        "x-nullable": true,
                        "name": "address",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "ar_assets_id",
                        "x-nullable": true,
                        "description": "ar assets",
                        "name": "ar_assets_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "id",
                        "x-nullable": true,
                        "description": "background",
                        "name": "business_card_background_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "会社",
                        "x-nullable": true,
                        "name": "business_card_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "id",
                        "x-nullable": true,
                        "description": "business card",
                        "name": "business_card_parts_coordinate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "会社名",
                        "x-nullable": true,
                        "name": "company_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "部署",
                        "x-nullable": true,
                        "name": "department",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "名前",
                        "x-nullable": true,
                        "name": "display_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "sample@example.com",
                        "x-nullable": true,
                        "name": "email",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "役職",
                        "x-nullable": true,
                        "name": "official_position",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "090-1234-5678",
                        "x-nullable": true,
                        "name": "phone_number",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "123-4567",
                        "x-nullable": true,
                        "name": "postal_code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "url",
                        "x-nullable": true,
                        "name": "qrcode_image_path",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BusinessCardResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "BusinessCard"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "BusinessCard ID",
                        "name": "business_card_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/users/three_dimentionals": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ThreeDimentionalModel"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ThreeDimentionalResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "ThreeDimentionalModel"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "3dmodel file to be uploaded",
                        "name": "ThreeDimentionalModel",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ThreeDimentionalResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/three_dimentionals/{three_dimentional_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ThreeDimentionalModel"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ThreeDimentional ID",
                        "name": "three_dimentional_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ThreeDimentionalResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "ThreeDimentionalModel"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ThreeDimentional ID",
                        "name": "three_dimentional_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "3dmodel file to be uploaded",
                        "name": "ThreeDimentionalModel",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ThreeDimentionalResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ThreeDimentionalModel"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ThreeDimentional ID",
                        "name": "three_dimentional_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/users/{user_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "update user",
                        "name": "CreateUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserRequest"
                        }
                    },
                    {
                        "type": "file",
                        "description": "Audio file to be uploaded",
                        "name": "recorded_voice",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer [Firebase JWT Token]",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ArAssetsResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "id"
                },
                "qrcode_image_path": {
                    "type": "string",
                    "example": "url"
                },
                "speaking_audio_path": {
                    "type": "string",
                    "example": "url"
                },
                "speaking_description": {
                    "type": "string",
                    "example": "description"
                },
                "three_dimentional_path": {
                    "type": "string",
                    "example": "url"
                }
            }
        },
        "dto.BackgroundResponse": {
            "type": "object",
            "properties": {
                "business_card_background_color": {
                    "type": "string",
                    "example": "#ffffff"
                },
                "business_card_background_image": {
                    "type": "string",
                    "example": "url"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.BusinessCardPartsCoordinate": {
            "type": "object",
            "properties": {
                "address_x": {
                    "type": "integer"
                },
                "address_y": {
                    "type": "integer"
                },
                "company_name_x": {
                    "type": "integer"
                },
                "company_name_y": {
                    "type": "integer"
                },
                "department_x": {
                    "type": "integer"
                },
                "department_y": {
                    "type": "integer"
                },
                "display_name_x": {
                    "type": "integer"
                },
                "display_name_y": {
                    "type": "integer"
                },
                "email_x": {
                    "type": "integer"
                },
                "email_y": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "official_position_x": {
                    "type": "integer"
                },
                "official_position_y": {
                    "type": "integer"
                },
                "phone_number_x": {
                    "type": "integer"
                },
                "phone_number_y": {
                    "type": "integer"
                },
                "postal_code_x": {
                    "type": "integer"
                },
                "postal_code_y": {
                    "type": "integer"
                },
                "qrcode_x": {
                    "type": "integer"
                },
                "qrcode_y": {
                    "type": "integer"
                }
            }
        },
        "dto.BusinessCardPartsCoordinateResponse": {
            "type": "object",
            "properties": {
                "address_x": {
                    "type": "integer"
                },
                "address_y": {
                    "type": "integer"
                },
                "company_name_x": {
                    "type": "integer"
                },
                "company_name_y": {
                    "type": "integer"
                },
                "department_x": {
                    "type": "integer"
                },
                "department_y": {
                    "type": "integer"
                },
                "display_name_x": {
                    "type": "integer"
                },
                "display_name_y": {
                    "type": "integer"
                },
                "email_x": {
                    "type": "integer"
                },
                "email_y": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "official_position_x": {
                    "type": "integer"
                },
                "official_position_y": {
                    "type": "integer"
                },
                "phone_number_x": {
                    "type": "integer"
                },
                "phone_number_y": {
                    "type": "integer"
                },
                "postal_code_x": {
                    "type": "integer"
                },
                "postal_code_y": {
                    "type": "integer"
                },
                "qrcode_x": {
                    "type": "integer"
                },
                "qrcode_y": {
                    "type": "integer"
                }
            }
        },
        "dto.BusinessCardResponse": {
            "type": "object",
            "properties": {
                "accessCount": {
                    "type": "integer"
                },
                "address": {
                    "type": "string"
                },
                "businessCardBackgroundColor": {
                    "description": "background",
                    "type": "string",
                    "example": "#ffffff"
                },
                "businessCardBackgroundImage": {
                    "type": "string",
                    "example": "url"
                },
                "businessCardName": {
                    "type": "string"
                },
                "businessCardPartsCoordinate": {
                    "description": "business card",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.BusinessCardPartsCoordinate"
                        }
                    ]
                },
                "companyName": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "officialPosition": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "speakingAudioPath": {
                    "type": "string"
                },
                "speakingDescription": {
                    "type": "string"
                },
                "threeDimentionalModel": {
                    "description": "ar assets",
                    "type": "string"
                }
            }
        },
        "dto.CreateBackgroundRequest": {
            "type": "object",
            "properties": {
                "business_card_background": {
                    "type": "string",
                    "example": "#ffffff"
                }
            }
        },
        "dto.CreateUserRequest": {
            "type": "object",
            "properties": {
                "is_toured": {
                    "type": "boolean",
                    "x-nullable": true,
                    "example": false
                }
            }
        },
        "dto.ThreeDimentionalResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_toured": {
                    "type": "boolean"
                },
                "recorded_model_path": {
                    "type": "string"
                },
                "recorded_voice_path": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "AIRship API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
