definitions:
  dto.CreateUserRequest:
    properties:
      id:
        type: string
    type: object
  dto.UserResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /user:
    post:
      parameters:
      - description: create user
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserResponse'
      tags:
      - User
  /user/:user_id:
    delete:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: delete user
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - User
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: update user
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - User
    put:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: update user
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      - description: update user
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - User
swagger: "2.0"
