definitions:
  dto.ArAssetsResponse:
    properties:
      id:
        example: id
        type: string
      qrcode_image_path:
        example: url
        type: string
      speaking_audio_path:
        example: url
        type: string
      speaking_description:
        example: description
        type: string
      three_dimentional_path:
        example: url
        type: string
    type: object
  dto.BusinessCardResponse:
    properties:
      accessCount:
        type: integer
      address:
        type: string
      businessCardBackground:
        type: string
      businessCardName:
        type: string
      businessCardPartsCoordinate:
        type: string
      companyName:
        type: string
      department:
        type: string
      displayName:
        type: string
      email:
        type: string
      id:
        type: string
      officialPosition:
        type: string
      phoneNumber:
        type: string
      postalCode:
        type: string
      speakingAudioPath:
        type: string
      speakingDescription:
        type: string
      threeDimentionalModel:
        type: string
    type: object
  dto.CreateArAssetsRequest:
    properties:
      speaking_description:
        example: description
        type: string
      three_dimentional_ID:
        example: url
        type: string
    type: object
  dto.CreateBusinessCardRequest:
    properties:
      address:
        example: 東京都渋谷区神南1-1-1
        type: string
        x-nullable: true
      business_card_background:
        example: '#ffffff'
        type: string
      business_card_name:
        example: 会社
        type: string
        x-nullable: true
      business_card_parts_coordinate:
        description: BusinessCardBackgroundImage *string `json:"business_card_background_image"
          example:"url" extensions:"x-nullable"`
        type: string
        x-nullable: true
      company_name:
        example: 会社名
        type: string
        x-nullable: true
      department:
        example: 部署
        type: string
        x-nullable: true
      display_name:
        example: 名前
        type: string
        x-nullable: true
      email:
        example: sample@example.com
        type: string
        x-nullable: true
      official_position:
        example: 役職
        type: string
        x-nullable: true
      phone_number:
        example: 090-1234-5678
        type: string
        x-nullable: true
      postal_code:
        example: 123-4567
        type: string
        x-nullable: true
    type: object
  dto.CreateUserRequest:
    properties:
      is_toured:
        example: false
        type: boolean
        x-nullable: true
    type: object
  dto.ThreeDimentionalResponse:
    properties:
      id:
        type: string
      path:
        type: string
    type: object
  dto.UserResponse:
    properties:
      id:
        type: string
      is_toured:
        type: boolean
      recorded_model_path:
        type: string
      recorded_voice_path:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: AIRship API
  version: "1.0"
paths:
  /ar_assets/{ar_assets_id}:
    get:
      parameters:
      - description: ArAssets ID
        in: path
        name: ar_assets_id
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ArAssetsResponse'
      tags:
      - ArAssets
  /user:
    delete:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - User
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - User
    post:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserResponse'
      tags:
      - User
    put:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: update user
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - User
  /user/ar_assets:
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ArAssetsResponse'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: Image file to be uploaded
        in: formData
        name: qrcodeImage
        required: true
        type: file
      - description: ArAssets
        in: body
        name: dto.CreateArAssetsRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateArAssetsRequest'
      responses:
        "201":
          description: Created
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
  /user/ar_assets/{ar_assets_id}:
    delete:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ArAssets ID
        in: path
        name: ar_assets_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ArAssets ID
        in: path
        name: ar_assets_id
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ArAssetsResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ArAssets
        in: body
        name: dto.CreateArAssetsRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateArAssetsRequest'
      - description: ArAssets ID
        in: path
        name: ar_assets_id
        required: true
        type: string
      - description: Image file to be uploaded
        in: formData
        name: qrcodeIcon
        type: file
      responses:
        "201":
          description: Created
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
  /user/business_card:
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.BusinessCardResponse'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: Image file to be uploaded
        in: formData
        name: BusinessCardBackgroundImage
        required: true
        type: file
      - description: BusinessCard
        in: body
        name: CreateBusinessCardRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateBusinessCardRequest'
      responses:
        "201":
          description: Created
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
  /user/business_card/{business_card_id}:
    delete:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: BusinessCard ID
        in: path
        name: business_card_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: BusinessCard ID
        in: path
        name: business_card_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BusinessCardResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: BusinessCard ID
        in: path
        name: business_card_id
        required: true
        type: string
      - description: Image file to be uploaded
        in: formData
        name: BusinessCardBackgroundImage
        required: true
        type: file
      - description: BusinessCard
        in: body
        name: CreateBusinessCardRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateBusinessCardRequest'
      responses:
        "201":
          description: Created
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
  /user/three_dimentional:
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ThreeDimentionalResponse'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: 3dmodel file to be uploaded
        in: formData
        name: ThreeDimentionalModel
        required: true
        type: file
      responses:
        "201":
          description: Created
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
  /user/three_dimentional/{three_dimentional_id}:
    delete:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ThreeDimentional ID
        in: path
        name: three_dimentional_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ThreeDimentional ID
        in: path
        name: three_dimentional_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ThreeDimentionalResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ThreeDimentional ID
        in: path
        name: three_dimentional_id
        required: true
        type: string
      - description: 3dmodel file to be uploaded
        in: formData
        name: ThreeDimentionalModel
        required: true
        type: file
      responses:
        "201":
          description: Created
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
swagger: "2.0"
