definitions:
  dto.ArAssetsResponse:
    properties:
      id:
        example: id
        type: string
      qrcode_image_path:
        example: url
        type: string
      speaking_audio_path:
        example: url
        type: string
      speaking_description:
        example: description
        type: string
      three_dimentional_path:
        example: url
        type: string
    type: object
  dto.BackgroundResponse:
    properties:
      business_card_background_color:
        example: '#ffffff'
        type: string
      business_card_background_image:
        example: url
        type: string
      id:
        type: string
    type: object
  dto.BusinessCardPartsCoordinate:
    properties:
      address_x:
        type: integer
      address_y:
        type: integer
      company_name_x:
        type: integer
      company_name_y:
        type: integer
      department_x:
        type: integer
      department_y:
        type: integer
      display_name_x:
        type: integer
      display_name_y:
        type: integer
      email_x:
        type: integer
      email_y:
        type: integer
      id:
        type: string
      official_position_x:
        type: integer
      official_position_y:
        type: integer
      phone_number_x:
        type: integer
      phone_number_y:
        type: integer
      postal_code_x:
        type: integer
      postal_code_y:
        type: integer
      qrcode_x:
        type: integer
      qrcode_y:
        type: integer
    type: object
  dto.BusinessCardPartsCoordinateResponse:
    properties:
      address_x:
        type: integer
      address_y:
        type: integer
      company_name_x:
        type: integer
      company_name_y:
        type: integer
      department_x:
        type: integer
      department_y:
        type: integer
      display_name_x:
        type: integer
      display_name_y:
        type: integer
      email_x:
        type: integer
      email_y:
        type: integer
      id:
        type: string
      official_position_x:
        type: integer
      official_position_y:
        type: integer
      phone_number_x:
        type: integer
      phone_number_y:
        type: integer
      postal_code_x:
        type: integer
      postal_code_y:
        type: integer
      qrcode_x:
        type: integer
      qrcode_y:
        type: integer
    type: object
  dto.BusinessCardResponse:
    properties:
      accessCount:
        type: integer
      address:
        type: string
      businessCardBackgroundColor:
        description: background
        example: '#ffffff'
        type: string
      businessCardBackgroundImage:
        example: url
        type: string
      businessCardName:
        type: string
      businessCardPartsCoordinate:
        allOf:
        - $ref: '#/definitions/dto.BusinessCardPartsCoordinate'
        description: business card
      companyName:
        type: string
      department:
        type: string
      displayName:
        type: string
      email:
        type: string
      id:
        type: string
      officialPosition:
        type: string
      phoneNumber:
        type: string
      postalCode:
        type: string
      speakingAudioPath:
        type: string
      speakingDescription:
        type: string
      threeDimentionalModel:
        description: ar assets
        type: string
    type: object
  dto.CreateUserRequest:
    properties:
      is_toured:
        example: false
        type: boolean
        x-nullable: true
    type: object
  dto.ThreeDimentionalResponse:
    properties:
      id:
        type: string
      path:
        type: string
    type: object
  dto.UserResponse:
    properties:
      id:
        type: string
      is_toured:
        type: boolean
      recorded_model_path:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: AIRship API
  version: "1.0"
paths:
  /v1/ar_assets/{ar_assets_id}:
    get:
      parameters:
      - description: ArAssets ID
        in: path
        name: ar_assets_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ArAssetsResponse'
      tags:
      - ArAssets
  /v1/business_card_parts_coordinates:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.BusinessCardPartsCoordinateResponse'
            type: array
      tags:
      - BusinessCardPartsCoordinate
  /v1/users:
    post:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: create user
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - User
  /v1/users/{user_id}:
    delete:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "204":
          description: No Content
      security:
      - ApiKeyAuth: []
      tags:
      - User
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - User
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: Audio file to be uploaded
        in: formData
        name: recorded_voice
        type: file
      - example: false
        in: formData
        name: is_toured
        type: boolean
        x-nullable: true
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - User
  /v1/users/ar_assets:
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ArAssetsResponse'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: Image file to be uploaded
        in: formData
        name: qrcodeIcon
        type: file
      - example: description
        in: formData
        name: speaking_description
        type: string
      - example: url
        in: formData
        name: three_dimentional_ID
        type: string
      responses:
        "201":
          description: Created
          headers:
            Location:
              description: /{ar_assets_id}
              type: string
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
  /v1/users/ar_assets/{ar_assets_id}:
    delete:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ArAssets ID
        in: path
        name: ar_assets_id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ArAssets ID
        in: path
        name: ar_assets_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ArAssetsResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - example: description
        in: formData
        name: speaking_description
        type: string
      - example: url
        in: formData
        name: three_dimentional_ID
        type: string
      - description: ArAssets ID
        in: path
        name: ar_assets_id
        required: true
        type: string
      - description: Image file to be uploaded
        in: formData
        name: qrcodeIcon
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ArAssetsResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - ArAssets
  /v1/users/business_card_backgrounds:
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.BackgroundResponse'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCardBackground
    post:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: Image file to be uploaded
        in: formData
        name: BusinessCardBackgroundImage
        required: true
        type: file
      - example: '#ffffff'
        in: formData
        name: business_card_background_color
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.BackgroundResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCardBackground
  /v1/users/business_cards:
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.BusinessCardResponse'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
    post:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - example: 東京都渋谷区神南1-1-1
        in: formData
        name: address
        type: string
        x-nullable: true
      - description: ar assets
        example: ar_assets_id
        in: formData
        name: ar_assets_id
        type: string
        x-nullable: true
      - description: background
        example: id
        in: formData
        name: business_card_background_id
        type: string
        x-nullable: true
      - example: 会社
        in: formData
        name: business_card_name
        type: string
        x-nullable: true
      - description: business card
        example: id
        in: formData
        name: business_card_parts_coordinate
        type: string
        x-nullable: true
      - example: 会社名
        in: formData
        name: company_name
        type: string
        x-nullable: true
      - example: 部署
        in: formData
        name: department
        type: string
        x-nullable: true
      - example: 名前
        in: formData
        name: display_name
        type: string
        x-nullable: true
      - example: sample@example.com
        in: formData
        name: email
        type: string
        x-nullable: true
      - example: 役職
        in: formData
        name: official_position
        type: string
        x-nullable: true
      - example: 090-1234-5678
        in: formData
        name: phone_number
        type: string
        x-nullable: true
      - example: 123-4567
        in: formData
        name: postal_code
        type: string
        x-nullable: true
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.BusinessCardResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
  /v1/users/business_cards/{business_card_id}:
    delete:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: BusinessCard ID
        in: path
        name: business_card_id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: BusinessCard ID
        in: path
        name: business_card_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BusinessCardResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: BusinessCard ID
        in: path
        name: business_card_id
        required: true
        type: string
      - description: Image file to be uploaded
        in: formData
        name: BusinessCardBackgroundImage
        required: true
        type: file
      - example: 東京都渋谷区神南1-1-1
        in: formData
        name: address
        type: string
        x-nullable: true
      - description: ar assets
        example: ar_assets_id
        in: formData
        name: ar_assets_id
        type: string
        x-nullable: true
      - description: background
        example: id
        in: formData
        name: business_card_background_id
        type: string
        x-nullable: true
      - example: 会社
        in: formData
        name: business_card_name
        type: string
        x-nullable: true
      - description: business card
        example: id
        in: formData
        name: business_card_parts_coordinate
        type: string
        x-nullable: true
      - example: 会社名
        in: formData
        name: company_name
        type: string
        x-nullable: true
      - example: 部署
        in: formData
        name: department
        type: string
        x-nullable: true
      - example: 名前
        in: formData
        name: display_name
        type: string
        x-nullable: true
      - example: sample@example.com
        in: formData
        name: email
        type: string
        x-nullable: true
      - example: 役職
        in: formData
        name: official_position
        type: string
        x-nullable: true
      - example: 090-1234-5678
        in: formData
        name: phone_number
        type: string
        x-nullable: true
      - example: 123-4567
        in: formData
        name: postal_code
        type: string
        x-nullable: true
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BusinessCardResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - BusinessCard
  /v1/users/three_dimentionals:
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ThreeDimentionalResponse'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: 3dmodel file to be uploaded
        in: formData
        name: ThreeDimentionalModel
        required: true
        type: file
      responses:
        "201":
          description: Created
          headers:
            Location:
              description: /{three_dimentional_id}
              type: string
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
  /v1/users/three_dimentionals/{three_dimentional_id}:
    delete:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ThreeDimentional ID
        in: path
        name: three_dimentional_id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
    get:
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ThreeDimentional ID
        in: path
        name: three_dimentional_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ThreeDimentionalResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer [Firebase JWT Token]
        in: header
        name: Authorization
        required: true
        type: string
      - description: ThreeDimentional ID
        in: path
        name: three_dimentional_id
        required: true
        type: string
      - description: 3dmodel file to be uploaded
        in: formData
        name: ThreeDimentionalModel
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ThreeDimentionalResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - ThreeDimentionalModel
swagger: "2.0"
